[package]
cjc-version = "1.3.0"
name = "cjls"
organization = ""
description = "nothing here"
version = "0.2.0"
target-dir = ""
script-dir = ""
output-type = "executable"
compile-option = "-O2 --static-std"
override-compile-option = ""
link-option = ""
# lsp_types is generated: every file imports what any of them may need
package-configuration = { cjls = { compile-option = "--static" }, "cjls.lsp_types" = { compile-option = "-Woff unused" } }

[dependencies]
calca = { path = "../calca" }
fjson = { path = "../fjson" }
jsonrpc = { path = "../jsonrpc" }
loupe = { path = "../loupe" }
rope = { path = "../rope" }
stdxx = { path = "../stdxx" }
