#!/usr/bin/env python3
"""Writes src/pow10_table.cj: 10^e for -348 <= e <= 347 as the 128 bits under its leading one,
rounded down - the table of Go's strconv (eisel_lemire.go), which `parseFloat64` reads.

    python3 modules/fnum/pow10_table.py > modules/fnum/src/pow10_table.cj
"""

from fractions import Fraction

MIN_EXP10 = -348
MAX_EXP10 = 347


def mantissa128(e: int) -> int:
    value = Fraction(10) ** e
    # the power of two that puts the leading one at bit 127
    shift = 127 - (value.numerator.bit_length() - value.denominator.bit_length())
    scaled = value * Fraction(2) ** shift
    m = scaled.numerator // scaled.denominator
    while m >= 1 << 128:
        shift -= 1
        scaled = value * Fraction(2) ** shift
        m = scaled.numerator // scaled.denominator
    while m < 1 << 127:
        shift += 1
        scaled = value * Fraction(2) ** shift
        m = scaled.numerator // scaled.denominator
    return m


def main() -> None:
    print("// Generated by `pow10_table.py` beside the manifest: do not edit.")
    print()
    print("package fnum")
    print()
    print(f"const POW10_MIN_EXP10: Int64 = {MIN_EXP10}")
    print(f"const POW10_MAX_EXP10: Int64 = {MAX_EXP10}")
    print()
    print("/**")
    print(" * For each `e` from `POW10_MIN_EXP10`, the low then the high 64 bits of `10^e` normalized to 128 bits, rounded down.")
    print(" * An `Array`, not a `VArray`: a global `VArray` is copied whole at every index.")
    print(" */")
    print("let POW10_128: Array<UInt64> = [")
    for e in range(MIN_EXP10, MAX_EXP10 + 1):
        m = mantissa128(e)
        print(f"    0x{m & ((1 << 64) - 1):016X}, 0x{m >> 64:016X},")
    print("]")


if __name__ == "__main__":
    main()
