"""What the servers are measured on: a cjpm project, generated or given."""

import pathlib
from dataclasses import dataclass

MANIFEST = """\
[package]
  cjc-version = "1.3.0"
  name = "bench"
  description = "generated by tests/perf"
  version = "1.0.0"
  output-type = "executable"

[dependencies]
"""

MAIN = """\
package bench

main(): Int64 {
    0
}
"""


def declarations(index: int) -> str:
    """A few declarations of every kind a document symbol has, numbered to keep names apart."""
    return f"""\
/** A class, its members, and what uses them. */
public open class Shape{index} {{
    public var name: String = "shape{index}"
    public init() {{}}
    public open func area(): Float64 {{
        let sides = [1.0, 2.0, 3.0]
        var total = 0.0
        for (side in sides) {{
            total += side * side
        }}
        total
    }}
}}

public struct Point{index} {{
    public let x: Int64
    public let y: Int64
    public init(x: Int64, y: Int64) {{
        this.x = x
        this.y = y
    }}
    public func distance(other: Point{index}): Int64 {{
        match ((this.x - other.x, this.y - other.y)) {{
            case (0, dy) => dy
            case (dx, 0) => dx
            case (dx, dy) => dx * dx + dy * dy
        }}
    }}
}}

public interface Named{index} {{
    func label(): String
}}

extend Shape{index} <: Named{index} {{
    public func label(): String {{ "${{name}}: ${{area()}}" }}
}}

public enum Color{index} {{
    | Red | Green | Blue(Int64)
}}

func use{index}(shape: Shape{index}, point: Point{index}): String {{
    let color = Color{index}.Blue(point.distance(Point{index}(1, 2)))
    shape.label()
}}

"""


def text(lines: int) -> str:
    """A file of about `lines` lines of ordinary Cangjie, the same every time."""
    header = "package bench\n\n"
    body = []
    count = header.count("\n")
    index = 0
    while count < lines:
        block = declarations(index)
        body.append(block)
        count += block.count("\n")
        index += 1
    return header + "".join(body)


@dataclass
class Workspace:
    root: pathlib.Path
    subject: pathlib.Path  # the file the scenarios open and edit

    @property
    def subject_text(self) -> str:
        return self.subject.read_text(encoding="utf-8")


def generate(directory: pathlib.Path, lines: int) -> Workspace:
    """A project of `main.cj` and one file of about `lines` lines, the subject."""
    source = directory / "src"
    source.mkdir(parents=True, exist_ok=True)
    (directory / "cjpm.toml").write_text(MANIFEST, encoding="utf-8")
    (source / "main.cj").write_text(MAIN, encoding="utf-8")
    subject = source / "subject.cj"
    subject.write_text(text(lines), encoding="utf-8")
    return Workspace(root=directory, subject=subject)


def existing(root: pathlib.Path, subject: pathlib.Path | None) -> Workspace:
    """A project of one's own; the subject is the file given, or its largest `.cj` file."""
    if subject is None:
        files = [path for path in root.rglob("*.cj") if "target" not in path.parts]
        if not files:
            raise ValueError(f"no .cj file under {root}")
        subject = max(files, key=lambda path: path.stat().st_size)
    return Workspace(root=root, subject=subject.resolve())
