[package]
cjc-version = "1.3.0"
name = "fjson"
organization = ""
description = "JSON read and written over bytes, without a tree"
version = "1.0.0"
target-dir = ""
script-dir = ""
output-type = "static"
compile-option = "-Woff unused -O2"
override-compile-option = ""
link-option = ""
package-configuration = {}

[dependencies]
