[package]
cjc-version = "1.3.0"
name = "cjsyntax"
organization = ""
description = "A lossless, error-tolerant Cangjie parser"
version = "0.1.0"
target-dir = ""
script-dir = ""
output-type = "static"
compile-option = "-Woff unused -O2"
override-compile-option = ""
link-option = ""
package-configuration = {}

[dependencies]
ginkgo = { path = "../ginkgo" }
